inherit_from: .rubocop_todo.yml

# For more configurations see  https://rubocop.readthedocs.io/en/latest/configuration/

AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - 'lib/browserstack/automate/api/status.rb'
    - 'lib/browserstack/automate/api/projects.rb'
    - 'lib/browserstack/automate/api/builds.rb'
    - 'lib/browserstack/automate/api/plan.rb'
    - 'lib/plan/client.rb'

Metrics/LineLength:
  Max: 140

Style/ClassAndModuleChildren:
  Description: Checks style of children classes and modules.
  StyleGuide: "#namespace-definition"
  SafeAutoCorrect: false
  AutoCorrect: false
  Enabled: false
  VersionAdded: '0.19'
  EnforcedStyle: nested
  SupportedStyles:
  - nested
  - compact

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Style/CommentedKeyword:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

